#partie base de donnees
- hosts: db
# Contient les valeurs des variables d'environement
  vars_files:
    - vars/main.yml
  tasks:
  - name: installation des sofwares necessaire au fonctionnement de la base de donnees
    apt:
      name:
        - python3-pip
        - python3-dev
        - libmariadb3
        - libmariadb-dev
  - name: Installation de la librairie Python MySQL et mariaDB
    pip:
      name:
        - mariadb
        - PyMySQL
 # Creation de l'utilisateur dedie
  - name: creation de l'utilisateur de la base de donnees
    mysql_user:
      name: "{{ database_user }}"
      password: "{{ database_password }}"
      priv: "*.*:ALL"
      host: "%"
      append_privs: yes
      state: present
      login_user: root
      login_password: '{{ mysql_root_password }}'
      login_unix_socket: /var/run/mysqld/mysqld.sock
  # Copie du fichier sql
  - name: Copy sql files
    ansible.builtin.copy:
      src: /files/sql/create_structure.sql
      dest: /root/create_structure.sql
  - name: Importation de la base de donnees
    mysql_db:
      name: "{{ database_name}}"
      state: import
      target: /root/create_structure.sql
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_user: root
      login_password: "{{ mysql_root_password }}"
  - name: ensure mysql is configured to bind to the specified address and port
    ini_file:
      dest: /etc/mysql/mariadb.cnf
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { section: mysqld, option: bind-address, value: 0.0.0.0 }
    register: my_cnf
  - name: Redemarrage de mysql
    service: name=mariadb state=restarted
# Partie application python
- hosts: python
  vars_files:
    - vars/main.yml
  vars:
    database_connection:
      - key: USER_DB
        value: "{{ database_user }}"
      - key: DB_PASSWORD
        value: "{{ database_password }}"
      - key: DB_NAME
        value: "{{ database_name }}"
      - key: DB_HOST
        value: "dbubuntu"
      - key: DB_PORT
        value: "3306"
  tasks:
  - name: Install Python and connect mariadb Ubuntu
    apt:
      name:
        - python3-pip
        - python3-dev
        - libmariadb3
        - libmariadb-dev
  # Installation du paquet pip
  - name: Install python mariadb
    pip:
      name: mariadb
  # Copy du code de l'application
  - name: Copy application files
    ansible.builtin.copy:
      src: /files/app/
      dest: /root/app/
  # Definition des variables d'environnement pour la connexion a la DB
  - name: customize /etc/environment
    ansible.builtin.lineinfile:
      dest: "/etc/environment"
      state: present
      regexp: "^{{ item.key }}="
      line: "{{ item.key }}={{ item.value }}"
    with_items: "{{ database_connection }}"
