CREATE DATABASE if not exists Registre_QCM;

USE Registre_QCM;

CREATE TABLE IF NOT EXISTS QCM (
    `id` INT(10) AUTO_INCREMENT PRIMARY KEY,
    `nom` VARCHAR(256) NOT NULL,  
);

CREATE TABLE IF NOT EXISTS question (
    `id` INT(10) AUTO_INCREMENT PRIMARY KEY,
    `intitule` VARCHAR(256) NOT NULL,  
    `rep_A` VARCHAR(256) NOT NULL,
    `rep_B` VARCHAR(256) NOT NULL, 
    `rep_C` VARCHAR(256) NOT NULL,  
    `QCM_id` INT(10),
    FOREIGN KEY (`QCM_id`) REFERENCES QCM(`id`) ON DELETE CASCADE
)
